### PR TITLE
Fix asap browser dependency in react-native env.

### PR DESCRIPTION
**Pull request by FrankSalad**
Lots of people, including myself, hit a roadblock importing asap. This fixes it!
Related issues:
https://github.com/kriskowal/asap/issues/64
https://github.com/facebook/react-native/issues/3463
https://github.com/facebook/react-native/pull/2208
https://github.com/Netflix/falcor/issues/603

### CODE REVIEW

**Comment by kriskowal** [comment]
Please document what this does, what interprets it, link to reference, and why its needed.

**Comment by psegalen** [comment]
Hello @kriskowal,
I ran into this issue too and the fix of @FrankSalad makes it go away!
Basically, your asap package can be used as a dependency in React Native which is a library to create native mobile applications with React and the code lines of this PR assure that asap is compatible with React Native.
I'd really like this crash to go away! :)

**Comment by idibidiart** [comment]
@psegalen I"m curious about the use case in the context of React Native. Can you share some code where asap is being used (how and why you use it in React Native?)

**Comment by psegalen** [comment]
My personal case is very specific, I use ReactXP which is a lib on top of React Native and React to create applications for web, iOS, Android and Windows with the same codebase.
I personally don't use asap but `promise` (https://github.com/then/promise) to make my web app support IE (promises aren't coming out of the box in IE, I have to use this polyfill), this package has a direct dependency on asap.
I found this PR by searching for this issue on Google, many users encountered this issue in other use cases, @FrankSalad linked some issues on both React Native and Falcor projects.

**Comment by vigzmv** [comment]
Please merge this issue.! Can't use clarifai due to this problem.

**Comment by kriskowal** [comment]
Very well. I will follow up with the needed work for CI and documentation. In the future, please amend the PR with the requested changes. You’ll note that because this project straddles so many runtime environments, every line documents not only what and how, but why and why not the alternatives.

**Comment by kriskowal** [comment]
Published 2.0.6.

Any of you ought to also follow up with React Native to inform that that configuring whether Node.js domains are supported on a per-package basis is not sensible. This package should work without modification if a.) React Native provides domains and uses the default modules or b.) React Native does not provide domains and observes the browserify convention of loading the "browser" modules mentioned in package.json.

**Pull request merged**
